### ISSUE TITLE
Attribute Error

### ISSUE THREAD

**Issue by akuptsov88** [freedomwebtech/yolov8-segment-egg-counter#1]
hi! i'm getting an error while trying to run:

output:
```
0: 320x640 15 EGGs, 453.8ms
Speed: 3.0ms preprocess, 453.8ms inference, 32.9ms postprocess per image at shape (1, 3, 320, 640)
Traceback (most recent call last):
  File "H:\Job\c\EggCounter\main1.py", line 35, in <module>
    bboxes, classes, segmentations, scores = ys.detect(frame)
  File "H:\Job\c\EggCounter\yolo_segmentation.py", line 21, in detect
    for seg in result.masks.segments:
  File "C:\Program Files\Python310\lib\site-packages\ultralytics\utils\__init__.py", line 162, in __getattr__
    raise AttributeError(f"'{name}' object has no attribute '{attr}'. See valid attributes below.\n{self.__doc__}")
AttributeError: 'Masks' object has no attribute 'segments'. See valid attributes below.

    A class for storing and manipulating detection masks.

    Attributes:
        xy (list): A list of segments in pixel coordinates.
        xyn (list): A list of normalized segments.

    Methods:
        cpu(): Returns the masks tensor on CPU memory.
        numpy(): Returns the masks tensor as a numpy array.
        cuda(): Returns the masks tensor on GPU memory.
        to(device, dtype): Returns the masks tensor with the specified device and dtype.
```

my python ver:
```
C:\Users\Admin1>python --version
Python 3.10.2
```

**Comment by akuptsov88** [comment]
i have ultralytics version 8.2.28, (and updated the python to 3.12.3 version)

so, 
in yolo_segmentation.py line 21:
`for seg in result.masks.segments:`
i changed to:
`for seg in result.masks.xyn:`

and that solved the issue
